In [2]:
!python --version

Python 3.7.6


In [3]:
def quicksort(arr):
    if len(arr) <=1:
        return arr
    pivot = arr[len(arr)//2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([11, 6, 4, 6, 9, 10]))

[4, 6, 6, 9, 10, 11]


In [4]:
x = 3
print(x, type(x))


3 <class 'int'>


# Numpy


In [5]:
import numpy as np

Arrays

In [6]:
a = np.array([5, 6, 7])
print(type(a), a.shape, *[a[x] for x in range(len(a))])

<class 'numpy.ndarray'> (3,) 5 6 7


In [7]:
a[0]= 88
print(a)

[88  6  7]


In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
print(len(b))

2


In [10]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [11]:
a = np.zeros((10, 10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
print(np.ones((1,2)))

[[1. 1.]]


In [13]:
print(np.full((2,2), 7))

[[7 7]
 [7 7]]


Create a 2x2 identity matrix

In [14]:
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [15]:
print(np.random.random((2,2)))

[[0.76521095 0.86507687]
 [0.37382519 0.12051055]]


Array Indexing 

In [16]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)

print(bool_idx)



[[False False]
 [ True  True]
 [ True  True]]


In [17]:
print(a[bool_idx])

[3 4 5 6]


In [18]:
print(a[a > 2])


[3 4 5 6]
