In [1]:
!python --version

Python 3.7.6


In [2]:
def quicksort(arr):
    if len(arr) <=1:
        return arr
    pivot = arr[len(arr)//2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([11, 6, 4, 6, 9, 10]))

[4, 6, 6, 9, 10, 11]


In [3]:
x = 3
print(x, type(x))


3 <class 'int'>


# Numpy


In [4]:
import numpy as np

## Arrays

In [5]:
a = np.array([5, 6, 7])
print(type(a), a.shape, *[a[x] for x in range(len(a))])

<class 'numpy.ndarray'> (3,) 5 6 7


In [6]:
a[0]= 88
print(a)

[88  6  7]


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(len(b))

2


In [9]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [10]:
a = np.zeros((10, 10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
print(np.ones((1,2)))

[[1. 1.]]


In [12]:
print(np.full((2,2), 7))

[[7 7]
 [7 7]]


Create a 2x2 identity matrix

In [13]:
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


print(np.random.random((2,2)))

 ### Array Indexing 

In [14]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)

print(bool_idx)



[[False False]
 [ True  True]
 [ True  True]]


In [15]:
print(a[bool_idx])

[3 4 5 6]


In [16]:
print(a[a > 2])


[3 4 5 6]


### Datatypes

In [17]:
x = np.array([1,2]) #let numpy choose the datatype
y = np.array([1.0, 2.0]) # Let numpy choose the datatype
z = np.array([1,2], dtype= np.str) # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 <U1


In [18]:
print(*z)

1 2


In [19]:
print(z)

['1' '2']


### Array Math

In [20]:

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [21]:
print(x - y, end= "\n\n")
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [22]:
#product
import time
print(time.strftime("%M:%S", time.localtime()))
print(x * y)
print(time.strftime("%M:%S", time.localtime()))
print(np.multiply(x,y))
print(time.strftime("%M:%S", time.localtime()))

19:09
[[ 5. 12.]
 [21. 32.]]
19:09
[[ 5. 12.]
 [21. 32.]]
19:09


In [23]:
print(x / y)
print(np.divide(x, y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [24]:
print(np.sqrt(x))


[[1.         1.41421356]
 [1.73205081 2.        ]]


In [25]:
v = np.array([9,10])
w = np.array([11, 12])
# inner product
print(v.dot(w))
print(np.dot(v, w))



219
219


In [26]:
# This @ operator in is equivalent to numpy's dot operator
print(v @ w)
print(x @ y)

219
[[19. 22.]
 [43. 50.]]


In [27]:
print(" Compute sum of all elements", np.sum(x))
print("Compute sum of each column", np.sum(x, axis=0), sep= " :")
print("Compute sum of each row", np.sum(x, axis=1),sep= " :")

Compute sum of all elements 10.0
Compute sum of each column :[4. 6.]
Compute sum of each row :[3. 7.]


In [28]:
print(x)
print("transpose",x.T, sep= "\n")


[[1. 2.]
 [3. 4.]]
transpose
[[1. 3.]
 [2. 4.]]


### Broadcasting




In [30]:
# Add a vector v to each row of the matrix x,
# sorting the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([99,99,99])
y = np.empty_like(x)  # Create a empty matrix with                          the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop 


for i in range(4):
    y[i, :] = x[i, :] + v

print(y)


[[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]]


In [38]:
vv = np.tile(v,(4,1))
print(vv)

[[99 99 99]
 [99 99 99]
 [99 99 99]
 [99 99 99]]


In [39]:
y = x + vv
print(y)

[[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]]


In [40]:
##Using braoadcast to do the same without creating any extra copy
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([99, 0, 99])
y = x + v # Add v to each row of x using broadcasting
print(y)

[[100   2 102]
 [103   5 105]
 [106   8 108]
 [109  11 111]]
